export const mockUsers = [
  {
    id: "u1",
    name: "Anna",
    age: 19,
    nationality: "India",
    major: "Electrical Engineering",
    hobbies: ['cooking', 'reading', 'gaming', 'soccer'],
    location: { latitude: 33.644517, longitude: -117.842088 },
    activeActivityId: "g1",
    joinedGroupId: "g1",
    radius: 500
  },
  {
    id: "u2",
    name: "Kenji",
    age: 23,
    nationality: "Germany",
    major: "Electrical Engineering",
    hobbies: ['cooking', 'reading', 'anime', 'photography'],
    location: { latitude: 33.644456, longitude: -117.841899 },
    activeActivityId: null,
    joinedGroupId: "g1",
    radius: 500
  },
  {
    id: "u3",
    name: "Sara",
    age: 27,
    nationality: "USA",
    major: "Art",
    hobbies: ['anime', 'travel', 'reading', 'music'],
    location: { latitude: 33.644766, longitude: -117.842371 },
    activeActivityId: null,
    joinedGroupId: "g1",
    radius: 500
  },
  {
    id: "u4",
    name: "Carlos",
    age: 20,
    nationality: "China",
    major: "Psychology",
    hobbies: ['soccer', 'cooking', 'travel'],
    location: { latitude: 33.6477, longitude: -117.844515 },
    activeActivityId: null,
    joinedGroupId: null,
    radius: 500
  },
  {
    id: "u5",
    name: "Yuki",
    age: 23,
    nationality: "India",
    major: "Math",
    hobbies: ['reading', 'anime', 'hiking'],
    location: { latitude: 33.645554, longitude: -117.841809 },
    activeActivityId: null,
    joinedGroupId: null,
    radius: 500
  },
  {
    id: "u6",
    name: "Amina",
    age: 18,
    nationality: "USA",
    major: "Computer Science",
    hobbies: ['travel', 'anime', 'hiking'],
    location: { latitude: 33.644741, longitude: -117.84453 },
    activeActivityId: null,
    joinedGroupId: null,
    radius: 500
  },
  {
    id: "u7",
    name: "Leo",
    age: 27,
    nationality: "India",
    major: "Economics",
    hobbies: ['gaming', 'drawing', 'travel'],
    location: { latitude: 33.645759, longitude: -117.842655 },
    activeActivityId: null,
    joinedGroupId: null,
    radius: 500
  },
  {
    id: "u8",
    name: "Fatima",
    age: 25,
    nationality: "Germany",
    major: "Electrical Engineering",
    hobbies: ['drawing', 'cooking', 'hiking'],
    location: { latitude: 33.648348, longitude: -117.843622 },
    activeActivityId: null,
    joinedGroupId: null,
    radius: 500
  },
  {
    id: "u9",
    name: "Jin",
    age: 24,
    nationality: "Nigeria",
    major: "Math",
    hobbies: ['hiking', 'gaming', 'reading'],
    location: { latitude: 33.64711, longitude: -117.842961 },
    activeActivityId: null,
    joinedGroupId: null,
    radius: 500
  },
  {
    id: "u10",
    name: "Elena",
    age: 23,
    nationality: "USA",
    major: "Art",
    hobbies: ['soccer', 'gaming'],
    location: { latitude: 33.647771, longitude: -117.842263 },
    activeActivityId: null,
    joinedGroupId: null,
    radius: 500
  },
  {
    id: "u11",
    name: "David",
    age: 26,
    nationality: "China",
    major: "Electrical Engineering",
    hobbies: ['gaming', 'photography'],
    location: { latitude: 33.645651, longitude: -117.841318 },
    activeActivityId: null,
    joinedGroupId: null,
    radius: 500
  },
  {
    id: "u12",
    name: "Nina",
    age: 22,
    nationality: "Japan",
    major: "Biology",
    hobbies: ['cooking', 'soccer', 'travel', 'drawing'],
    location: { latitude: 33.644423, longitude: -117.841137 },
    activeActivityId: null,
    joinedGroupId: null,
    radius: 500
  },
  {
    id: "u13",
    name: "Hassan",
    age: 28,
    nationality: "France",
    major: "Economics",
    hobbies: ['anime', 'reading'],
    location: { latitude: 33.64501, longitude: -117.841622 },
    activeActivityId: null,
    joinedGroupId: null,
    radius: 500
  },
  {
    id: "u14",
    name: "Sofia",
    age: 25,
    nationality: "China",
    major: "Computer Science",
    hobbies: ['cooking', 'hiking'],
    location: { latitude: 33.647402, longitude: -117.842329 },
    activeActivityId: null,
    joinedGroupId: null,
    radius: 500
  },
  {
    id: "u15",
    name: "Tariq",
    age: 26,
    nationality: "France",
    major: "Math",
    hobbies: ['photography', 'hiking', 'reading', 'drawing'],
    location: { latitude: 33.645306, longitude: -117.844723 },
    activeActivityId: null,
    joinedGroupId: null,
    radius: 500
  },
  {
    id: "u16",
    name: "Maya",
    age: 27,
    nationality: "China",
    major: "Art",
    hobbies: ['hiking', 'reading'],
    location: { latitude: 33.645308, longitude: -117.84273 },
    activeActivityId: null,
    joinedGroupId: null,
    radius: 500
  },
  {
    id: "u17",
    name: "Lucas",
    age: 23,
    nationality: "Mexico",
    major: "Computer Science",
    hobbies: ['soccer', 'reading'],
    location: { latitude: 33.645583, longitude: -117.8448 },
    activeActivityId: null,
    joinedGroupId: null,
    radius: 500
  },
  {
    id: "u18",
    name: "Aya",
    age: 21,
    nationality: "India",
    major: "Math",
    hobbies: ['music', 'reading'],
    location: { latitude: 33.647955, longitude: -117.844463 },
    activeActivityId: null,
    joinedGroupId: null,
    radius: 500
  },
  {
    id: "u19",
    name: "Omar",
    age: 22,
    nationality: "USA",
    major: "Electrical Engineering",
    hobbies: ['soccer', 'anime', 'music'],
    location: { latitude: 33.645849, longitude: -117.841732 },
    activeActivityId: null,
    joinedGroupId: null,
    radius: 500
  },
  {
    id: "u20",
    name: "Lena",
    age: 27,
    nationality: "USA",
    major: "Economics",
    hobbies: ['drawing', 'anime', 'soccer'],
    location: { latitude: 33.644514, longitude: -117.841285 },
    activeActivityId: null,
    joinedGroupId: null,
    radius: 500
  },
];
